meta_product_name: "InTouch"
meta_title: "InTouch - Plan it, code it, share it !"
meta_description: "The best tool to send automate recap for your clients"
meta_image: "cover_picture.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
