:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
  - webhook
:schedule:
  notifications:
    cron: '30 14 * * 3'   # '30 14 * * 3'
    class: NotificationsSchedulerJob
