:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
  - webhook
:schedule:
  notifications:
    # every: ['7d', first_in: '4h']
    cron: '* 7 * * 1' # tout les lundis à 7h
    class: NotificationsSchedulerJob
